server:
  port: 10010 #服务端口
spring: 
  application:  
    name: api-gateway #指定服务名
    
eureka:
  client:
    #因为是客户端，默认可以不配，所以以下就注释掉了
    #register-with-eureka: true #是否将自己注册到eureka服务中,默认为true
    #fetch-registry: true #是否从eureka服务中拉取其它服务的信息 ,默认为true
    
    service-url: #Eureka客户端与Eureka服务端交互地址
       defaultZone:  http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka #Eureka注册中心的地址
    registry-fetch-interval-seconds: 5 #每隔5秒从EurekaServer获取新的服务列表，默认为30秒
  instance:
    prefer-ip-address: true #将自己的ip注册到Eureka服务中
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port} #指定实例Id，一个服务下面可以有多个实例，即eureka服务可以有集群

zuul:
  routes:
    spring-cloud-order: # 这里是路由id，随意写
      path: /spring-cloud-order/** # 这里是映射路径
      serviceId: spring-cloud-order # 指定服务名称