server:
  port: 10010 #服务端口
spring: 
  application:  
    name: api-gateway #指定服务名
    
zuul:
  routes:
    spring-cloud-order: # 这里是路由id，随意写
      path: /spring-cloud-order/** # 这里是映射路径
      url: http://127.0.0.1:10089 # 映射路径对应的实际url地址