server:
  port: 10011 #服务端口

spring:
  application:
    name: springcloudconfig  #指定服务名  
  cloud:
    config:
      server:
        git:
          basedir: D:/studySpace/springCloudDemo/springcloud-config/application
          uri: git@github.com:HoldingTheTomcat/userconfig.git #默认配置
          search-paths: '{application}'  #需要在userconfig仓库创建application占位符对应的文件夹，并在该文件下，创建application对应的文件
                                         #config客户端用的时候，name就是对应的application,
                                         #这样就可以实现不同项目根据不同文件夹区分，而不用创建多个仓库来区分

  security:
    user:
      name: admin
      password: 123456

eureka:
  client: #客户端信息
    #因为是客户端，默认可以不配，所以以下就注释掉了
    #register-with-eureka: true #是否将自己注册到eureka服务中,默认为true
    #fetch-registry: true #是否从eureka服务中拉取其它服务的信息 ,默认为true

    service-url: #Eureka客户端与Eureka服务端交互地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka #将自己注册到Eureka集群上，注册中心的地址

  instance: #实例信息
    prefer-ip-address: true #当你获取host时，返回的是ip,而不是主机名
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port} #指定实例Id，一个服务下面可以有多个实例，即eureka服务可以有集群
    lease-expiration-duration-in-seconds: 10 # 如果超过10秒没有发送心跳，EurekaServer就会认为该服务宕机，会从服务列表中移除,服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 5 # 每5秒一次，向注册中心发送心跳，服务续约(renew)的间隔，默认为30秒

#暴露bus的接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true

logging:
  level: 
    root: debug